(function(global, undefined) {
  function mockRandom(value, callback) {
    // Mock Math.round because the random number is generated by Math.round(Math.random())
    var _round = Math.round
    Math.round = function() {
      return value
    }

    callback()

    Math.round = _round
  }

  module.exports = {
    mockRandom: mockRandom,
  }

})(this)